### ISSUE TITLE
你好，我照着步骤走，yarn build:types 报错 Could not find a declaration file for module 'history'. 

### ISSUE THREAD

**Issue by bigTig** [worldzhao/blog#14]
![Snipaste_2022-03-03_17-36-18](https://user-images.githubusercontent.com/80088198/156537567-bb139bc5-d439-4437-90ed-4b8ed4717dad.png)

大佬，请问这是什么原因呀，试了好多次，一直都报这个错。
我是按着步骤操作。

**Comment by worldzhao** [comment]
看起来是 react-router-dom 类型声明的版本冲突了，在 package.json 里使用 yarn resolutions 统一 @types/react-router-dom 的版本
